GCC=g++

INCLUDE_DIR= -I/usr/local/include/opencv4 -L/usr/local/lib/
LIBS =  -lopencv_highgui -lopencv_core -lopencv_imgproc
FLAGS = -O3 
all:
	#$(GCC) $(INCLUDE_DIR) $(LIB_DIR) $(LIBS) $(FLAGS) mcc.cpp Convert_Vetor.cpp -o convertVetor
	#$(GCC) teste_class.cpp -o teste_class mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   
	



	#---------------------------------------- versão anterior das libs ----------------------------------------------------
	#---------------------------------------- verificar backup source -----------------------------------------------------
	#$(GCC) indexing_search.cpp -o indexing_search mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   
	#$(GCC) generate_words.cpp -o generate_words mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   


	#$(GCC) teste_search_id.cpp -o teste_search_id mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   
	#$(GCC) teste_search_scroll.cpp -o teste_search_scroll mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   
	#$(GCC) Parameters_Testing_Indexing_Search.cpp -o Parameters_Testing mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   

	#$(GCC) Testing_Search_Index_Words.cpp -o Testing_Index_Search mcc_vector/mcc.cpp Indexing/Indexing.cpp $(INCLUDE_DIR) $(LIBS) $(FLAGS)   

	$(GCC) generate_vector_python.cpp -o generate_vector_python mcc_vector/mcc.cpp Indexing/Person.h $(INCLUDE_DIR) $(LIBS) $(FLAGS)   





#Rodar threshould de pesos
#
